services:
  db-dev:
    container_name: trash-manager-db
    image: postgres:latest
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432
  web-dev:
    container_name: trash-manager-web
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    env_file:
      - ./.env
    volumes:
      - web_data:/app
    ports:
      - 8000:8000
    restart: unless-stopped
    command: ["poetry", "run", "trash_manager/manage.py", "runserver", "0.0.0.0:8000"]
volumes:
  postgres_data:
  web_data:
