services:
  db-dev:
    container_name: trash-manager-db
    image: postgres:latest
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432
  web-dev:
    container_name: trash-manager-web
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    env_file:
      - ./.env
    volumes:
      - web_data:/app
    restart: unless-stopped

volumes:
  postgres_data:
  web_data:
